// AUTOGENERATED: DO NOT EDIT
#pragma once

#include "typeinfo.h"

Type_Info const *typeinfo_of_char(void);
Type_Info const *typeinfo_of_unsigned_char(void);
Type_Info const *typeinfo_of_short(void);
Type_Info const *typeinfo_of_unsigned_short(void);
Type_Info const *typeinfo_of_int(void);
Type_Info const *typeinfo_of_unsigned_int(void);
Type_Info const *typeinfo_of_long(void);
Type_Info const *typeinfo_of_unsigned_long(void);
Type_Info const *typeinfo_of_long_long(void);
Type_Info const *typeinfo_of_unsigned_long_long(void);
Type_Info const *typeinfo_of_float(void);
Type_Info const *typeinfo_of_double(void);
Type_Info const *typeinfo_of_struct_base__(void);
Type_Info const *typeinfo_of_struct_base(void);
Type_Info const *typeinfo_of_struct_(unnamed_at_test.h:10:9)(void);

#define typeinfo_of(T) \
    _Generic((T), \
        char: typeinfo_of_char, \
        unsigned char: typeinfo_of_unsigned_char, \
        short: typeinfo_of_short, \
        unsigned short: typeinfo_of_unsigned_short, \
        int: typeinfo_of_int, \
        unsigned int: typeinfo_of_unsigned_int, \
        long: typeinfo_of_long, \
        unsigned long: typeinfo_of_unsigned_long, \
        long long: typeinfo_of_long_long, \
        unsigned long long: typeinfo_of_unsigned_long_long, \
        float: typeinfo_of_float, \
        double: typeinfo_of_double, \
        struct base *: typeinfo_of_struct_base__, \
        struct base: typeinfo_of_struct_base, \
        struct (unnamed at test.h:10:9): typeinfo_of_struct_(unnamed_at_test.h:10:9)  \
    )()

#ifdef TYPEINFO_IMPLEMENTATION
// forward declarations (many types are self-referential)
static const Type_Info info_for_char;
static const Type_Info info_for_unsigned_char;
static const Type_Info info_for_short;
static const Type_Info info_for_unsigned_short;
static const Type_Info info_for_int;
static const Type_Info info_for_unsigned_int;
static const Type_Info info_for_long;
static const Type_Info info_for_unsigned_long;
static const Type_Info info_for_long_long;
static const Type_Info info_for_unsigned_long_long;
static const Type_Info info_for_float;
static const Type_Info info_for_double;
static const Type_Info info_for_struct_base__;
static const Type_Info info_for_struct_base;
static const Type_Info info_for_struct_(unnamed_at_test.h:10:9);

// Type info for: 'char'
static const Type_Info info_for_char = {
    .name = {"char", 4},
    .kind = TYPE_INTEGER,
    .size = 1,
    .alignment = 1,
    .integer = {.byte_width = 1, .is_signed = true},
};

Type_Info const *typeinfo_of_char(void) {
    return &info_for_char;
}

// Type info for: 'unsigned char'
static const Type_Info info_for_unsigned_char = {
    .name = {"unsigned char", 13},
    .kind = TYPE_INTEGER,
    .size = 1,
    .alignment = 1,
    .integer = {.byte_width = 1, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_char(void) {
    return &info_for_unsigned_char;
}

// Type info for: 'short'
static const Type_Info info_for_short = {
    .name = {"short", 5},
    .kind = TYPE_INTEGER,
    .size = 2,
    .alignment = 2,
    .integer = {.byte_width = 2, .is_signed = true},
};

Type_Info const *typeinfo_of_short(void) {
    return &info_for_short;
}

// Type info for: 'unsigned short'
static const Type_Info info_for_unsigned_short = {
    .name = {"unsigned short", 14},
    .kind = TYPE_INTEGER,
    .size = 2,
    .alignment = 2,
    .integer = {.byte_width = 2, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_short(void) {
    return &info_for_unsigned_short;
}

// Type info for: 'int'
static const Type_Info info_for_int = {
    .name = {"int", 3},
    .kind = TYPE_INTEGER,
    .size = 4,
    .alignment = 4,
    .integer = {.byte_width = 4, .is_signed = true},
};

Type_Info const *typeinfo_of_int(void) {
    return &info_for_int;
}

// Type info for: 'unsigned int'
static const Type_Info info_for_unsigned_int = {
    .name = {"unsigned int", 12},
    .kind = TYPE_INTEGER,
    .size = 4,
    .alignment = 4,
    .integer = {.byte_width = 4, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_int(void) {
    return &info_for_unsigned_int;
}

// Type info for: 'long'
static const Type_Info info_for_long = {
    .name = {"long", 4},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .integer = {.byte_width = 8, .is_signed = true},
};

Type_Info const *typeinfo_of_long(void) {
    return &info_for_long;
}

// Type info for: 'unsigned long'
static const Type_Info info_for_unsigned_long = {
    .name = {"unsigned long", 13},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .integer = {.byte_width = 8, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_long(void) {
    return &info_for_unsigned_long;
}

// Type info for: 'long long'
static const Type_Info info_for_long_long = {
    .name = {"long long", 9},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .integer = {.byte_width = 8, .is_signed = true},
};

Type_Info const *typeinfo_of_long_long(void) {
    return &info_for_long_long;
}

// Type info for: 'unsigned long long'
static const Type_Info info_for_unsigned_long_long = {
    .name = {"unsigned long long", 18},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .integer = {.byte_width = 8, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_long_long(void) {
    return &info_for_unsigned_long_long;
}

// Type info for: 'float'
static const Type_Info info_for_float = {
    .name = {"float", 5},
    .kind = TYPE_REAL,
    .size = 4,
    .alignment = 4,
    .real = {.byte_width = 4},
};

Type_Info const *typeinfo_of_float(void) {
    return &info_for_float;
}

// Type info for: 'double'
static const Type_Info info_for_double = {
    .name = {"double", 6},
    .kind = TYPE_REAL,
    .size = 8,
    .alignment = 8,
    .real = {.byte_width = 8},
};

Type_Info const *typeinfo_of_double(void) {
    return &info_for_double;
}

// Type info for: 'struct base *'
static const Type_Info info_for_struct_base__ = {
    .name = {"struct base *", 13},
    .kind = TYPE_POINTER,
    .size = 1,
    .alignment = 1,
    .pointer = {.inner = &info_for_struct_base},
};

Type_Info const *typeinfo_of_struct_base__(void) {
    return &info_for_struct_base__;
}

// Type info for: 'struct base'
static const Type_Record_Field fields_of_struct_base[2] = {
    {.name = {"next", 4}, .offset = 65535, .type = &info_for_struct_base__},
    {.name = {"type_name", 9}, .offset = 65535, .type = &info_for_int},
};
static const Type_Info info_for_struct_base = {
    .name = {"struct base", 11},
    .kind = TYPE_RECORD,
    .size = 1,
    .alignment = 1,
    .record = {.field_count = 2, .fields = fields_of_struct_base},
};

Type_Info const *typeinfo_of_struct_base(void) {
    return &info_for_struct_base;
}

// Type info for: 'struct (unnamed at test.h:10:9)'
static const Type_Record_Field fields_of_struct_(unnamed_at_test.h:10:9)[3] = {
    {.name = {"base", 4}, .offset = 65535, .type = &info_for_struct_base},
    {.name = {"name", 4}, .offset = 65535, .type = &info_for_int},
    {.name = {"age", 3}, .offset = 65535, .type = &info_for_float},
};
static const Type_Info info_for_struct_(unnamed_at_test.h:10:9) = {
    .name = {"struct (unnamed at test.h:10:9)", 31},
    .kind = TYPE_RECORD,
    .size = 1,
    .alignment = 1,
    .record = {.field_count = 3, .fields = fields_of_struct_(unnamed_at_test.h:10:9)},
};

Type_Info const *typeinfo_of_struct_(unnamed_at_test.h:10:9)(void) {
    return &info_for_struct_(unnamed_at_test.h:10:9);
}

#endif // TYPEINFO_IMPLEMENTATION

