(* NOTE: we allow trailing commas, but that is not in the grammar *)

file = package_decl, { top_level_decl } ;

package_decl   = "package", ID ;
top_level_decl = func_decl
               | var_decl
               | def_decl
               ;

func_decl = "func", func_id, [ func_generic_args ],
            "(", [ func_args ], ")" [ func_ret ] func_body ;

func_id                 = ID, { ".", ID } ;
func_generic_args       = "[", func_generic_args_items, "]" ;
func_generic_args_items = ID, [ ":", expr ], { ",", func_generic_args_items } ;
func_args               = ID, ":", expr, { ",", func_args } ;
func_ret                = expr
                        | "(", (func_ret_pack | func_named_ret_pack), ")" ;
func_ret_pack           = expr, { ",", expr } ;
func_named_ret_pack     = ID, ":", expr, { ",", func_named_ret_pack } ;

(* statements *)

(* expressions *)

field = expr, ".", ID ;

ID = ? [a-zA-Z_][a-zA-Z_0-9]+ ?
