// AUTOGENERATED: DO NOT EDIT
#pragma once

#include "typeinfo.h"

Type_Info const *typeinfo_of_char(void);
Type_Info const *typeinfo_of_unsigned_char(void);
Type_Info const *typeinfo_of_short(void);
Type_Info const *typeinfo_of_unsigned_short(void);
Type_Info const *typeinfo_of_int(void);
Type_Info const *typeinfo_of_unsigned_int(void);
Type_Info const *typeinfo_of_long(void);
Type_Info const *typeinfo_of_unsigned_long(void);
Type_Info const *typeinfo_of_long_long(void);
Type_Info const *typeinfo_of_unsigned_long_long(void);
Type_Info const *typeinfo_of_float(void);
Type_Info const *typeinfo_of_double(void);
Type_Info const *typeinfo_of_max_align_t(void);
Type_Info const *typeinfo_of_string_view(void);
Type_Info const *typeinfo_of_const_char__(void);
Type_Info const *typeinfo_of_struct_base__(void);
Type_Info const *typeinfo_of_struct_base(void);
Type_Info const *typeinfo_of_Named(void);
Type_Info const *typeinfo_of_inval(void);
Type_Info const *typeinfo_of___fsid_t(void);
Type_Info const *typeinfo_of_char__(void);
Type_Info const *typeinfo_of_Type_Integer(void);
Type_Info const *typeinfo_of_Type_Real(void);
Type_Info const *typeinfo_of_const_Type_Info__(void);
Type_Info const *typeinfo_of_Type_Pointer(void);
Type_Info const *typeinfo_of_const_Type_Record_Field__(void);
Type_Info const *typeinfo_of_Type_Record(void);
Type_Info const *typeinfo_of_const_Type_Union_Field__(void);
Type_Info const *typeinfo_of_Type_Union(void);
Type_Info const *typeinfo_of_Type_Info_As(void);
Type_Info const *typeinfo_of_struct_Type_Info(void);
Type_Info const *typeinfo_of_Type_Record_Field(void);
Type_Info const *typeinfo_of_Type_Union_Field(void);

#define typeinfo_of(T) \
    _Generic((T), \
        char: typeinfo_of_char, \
        unsigned char: typeinfo_of_unsigned_char, \
        short: typeinfo_of_short, \
        unsigned short: typeinfo_of_unsigned_short, \
        int: typeinfo_of_int, \
        unsigned int: typeinfo_of_unsigned_int, \
        long: typeinfo_of_long, \
        unsigned long: typeinfo_of_unsigned_long, \
        long long: typeinfo_of_long_long, \
        unsigned long long: typeinfo_of_unsigned_long_long, \
        float: typeinfo_of_float, \
        double: typeinfo_of_double, \
        max_align_t: typeinfo_of_max_align_t, \
        string_view: typeinfo_of_string_view, \
        const char *: typeinfo_of_const_char__, \
        struct base *: typeinfo_of_struct_base__, \
        struct base: typeinfo_of_struct_base, \
        Named: typeinfo_of_Named, \
        __fsid_t: typeinfo_of___fsid_t, \
        char *: typeinfo_of_char__, \
        Type_Integer: typeinfo_of_Type_Integer, \
        Type_Real: typeinfo_of_Type_Real, \
        const Type_Info *: typeinfo_of_const_Type_Info__, \
        Type_Pointer: typeinfo_of_Type_Pointer, \
        const Type_Record_Field *: typeinfo_of_const_Type_Record_Field__, \
        Type_Record: typeinfo_of_Type_Record, \
        const Type_Union_Field *: typeinfo_of_const_Type_Union_Field__, \
        Type_Union: typeinfo_of_Type_Union, \
        Type_Info_As: typeinfo_of_Type_Info_As, \
        struct Type_Info: typeinfo_of_struct_Type_Info, \
        Type_Record_Field: typeinfo_of_Type_Record_Field, \
        Type_Union_Field: typeinfo_of_Type_Union_Field  \
    )()

#ifdef TYPEINFO_IMPLEMENTATION
// forward declarations (many types are self-referential)
static const Type_Info info_for_char;
static const Type_Info info_for_unsigned_char;
static const Type_Info info_for_short;
static const Type_Info info_for_unsigned_short;
static const Type_Info info_for_int;
static const Type_Info info_for_unsigned_int;
static const Type_Info info_for_long;
static const Type_Info info_for_unsigned_long;
static const Type_Info info_for_long_long;
static const Type_Info info_for_unsigned_long_long;
static const Type_Info info_for_float;
static const Type_Info info_for_double;
static const Type_Info info_for_max_align_t;
static const Type_Info info_for_string_view;
static const Type_Info info_for_const_char__;
static const Type_Info info_for_struct_base__;
static const Type_Info info_for_struct_base;
static const Type_Info info_for_Named;
static const Type_Info info_for_inval;
static const Type_Info info_for___fsid_t;
static const Type_Info info_for_char__;
static const Type_Info info_for_Type_Integer;
static const Type_Info info_for_Type_Real;
static const Type_Info info_for_const_Type_Info__;
static const Type_Info info_for_Type_Pointer;
static const Type_Info info_for_const_Type_Record_Field__;
static const Type_Info info_for_Type_Record;
static const Type_Info info_for_const_Type_Union_Field__;
static const Type_Info info_for_Type_Union;
static const Type_Info info_for_Type_Info_As;
static const Type_Info info_for_struct_Type_Info;
static const Type_Info info_for_Type_Record_Field;
static const Type_Info info_for_Type_Union_Field;

// Type info for: 'char'
static const Type_Info info_for_char = {
    .name = {"char", 4},
    .kind = TYPE_INTEGER,
    .size = 1,
    .alignment = 1,
    .as.integer = {.byte_width = 1, .is_signed = true},
};

Type_Info const *typeinfo_of_char(void) {
    return &info_for_char;
}

// Type info for: 'unsigned char'
static const Type_Info info_for_unsigned_char = {
    .name = {"unsigned char", 13},
    .kind = TYPE_INTEGER,
    .size = 1,
    .alignment = 1,
    .as.integer = {.byte_width = 1, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_char(void) {
    return &info_for_unsigned_char;
}

// Type info for: 'short'
static const Type_Info info_for_short = {
    .name = {"short", 5},
    .kind = TYPE_INTEGER,
    .size = 2,
    .alignment = 2,
    .as.integer = {.byte_width = 2, .is_signed = true},
};

Type_Info const *typeinfo_of_short(void) {
    return &info_for_short;
}

// Type info for: 'unsigned short'
static const Type_Info info_for_unsigned_short = {
    .name = {"unsigned short", 14},
    .kind = TYPE_INTEGER,
    .size = 2,
    .alignment = 2,
    .as.integer = {.byte_width = 2, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_short(void) {
    return &info_for_unsigned_short;
}

// Type info for: 'int'
static const Type_Info info_for_int = {
    .name = {"int", 3},
    .kind = TYPE_INTEGER,
    .size = 4,
    .alignment = 4,
    .as.integer = {.byte_width = 4, .is_signed = true},
};

Type_Info const *typeinfo_of_int(void) {
    return &info_for_int;
}

// Type info for: 'unsigned int'
static const Type_Info info_for_unsigned_int = {
    .name = {"unsigned int", 12},
    .kind = TYPE_INTEGER,
    .size = 4,
    .alignment = 4,
    .as.integer = {.byte_width = 4, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_int(void) {
    return &info_for_unsigned_int;
}

// Type info for: 'long'
static const Type_Info info_for_long = {
    .name = {"long", 4},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .as.integer = {.byte_width = 8, .is_signed = true},
};

Type_Info const *typeinfo_of_long(void) {
    return &info_for_long;
}

// Type info for: 'unsigned long'
static const Type_Info info_for_unsigned_long = {
    .name = {"unsigned long", 13},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .as.integer = {.byte_width = 8, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_long(void) {
    return &info_for_unsigned_long;
}

// Type info for: 'long long'
static const Type_Info info_for_long_long = {
    .name = {"long long", 9},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .as.integer = {.byte_width = 8, .is_signed = true},
};

Type_Info const *typeinfo_of_long_long(void) {
    return &info_for_long_long;
}

// Type info for: 'unsigned long long'
static const Type_Info info_for_unsigned_long_long = {
    .name = {"unsigned long long", 18},
    .kind = TYPE_INTEGER,
    .size = 8,
    .alignment = 8,
    .as.integer = {.byte_width = 8, .is_signed = false},
};

Type_Info const *typeinfo_of_unsigned_long_long(void) {
    return &info_for_unsigned_long_long;
}

// Type info for: 'float'
static const Type_Info info_for_float = {
    .name = {"float", 5},
    .kind = TYPE_REAL,
    .size = 4,
    .alignment = 4,
    .as.real = {.byte_width = 4},
};

Type_Info const *typeinfo_of_float(void) {
    return &info_for_float;
}

// Type info for: 'double'
static const Type_Info info_for_double = {
    .name = {"double", 6},
    .kind = TYPE_REAL,
    .size = 8,
    .alignment = 8,
    .as.real = {.byte_width = 8},
};

Type_Info const *typeinfo_of_double(void) {
    return &info_for_double;
}

// Type info for: 'max_align_t'
static const Type_Record_Field fields_of_max_align_t[0] = {
};
static const Type_Info info_for_max_align_t = {
    .name = {"max_align_t", 11},
    .kind = TYPE_RECORD,
    .size = 32,
    .alignment = 16,
    .as.record = {.field_count = 0, .fields = fields_of_max_align_t},
};

Type_Info const *typeinfo_of_max_align_t(void) {
    return &info_for_max_align_t;
}

// Type info for: 'string_view'
static const Type_Record_Field fields_of_string_view[0] = {
};
static const Type_Info info_for_string_view = {
    .name = {"string_view", 11},
    .kind = TYPE_RECORD,
    .size = 16,
    .alignment = 8,
    .as.record = {.field_count = 0, .fields = fields_of_string_view},
};

Type_Info const *typeinfo_of_string_view(void) {
    return &info_for_string_view;
}

// Type info for: 'const char *'
static const Type_Info info_for_const_char__ = {
    .name = {"const char *", 12},
    .kind = TYPE_POINTER,
    .size = 1,
    .alignment = 1,
    .as.pointer = {.inner = &info_for_char},
};

Type_Info const *typeinfo_of_const_char__(void) {
    return &info_for_const_char__;
}

// Type info for: 'struct base *'
static const Type_Info info_for_struct_base__ = {
    .name = {"struct base *", 13},
    .kind = TYPE_POINTER,
    .size = 24,
    .alignment = 8,
    .as.pointer = {.inner = &info_for_struct_base},
};

Type_Info const *typeinfo_of_struct_base__(void) {
    return &info_for_struct_base__;
}

// Type info for: 'struct base'
static const Type_Record_Field fields_of_struct_base[2] = {
    {.name = {"next", 4}, .offset = 0, .type = &info_for_struct_base__},
    {.name = {"type_name", 9}, .offset = 8, .type = &info_for_string_view},
};
static const Type_Info info_for_struct_base = {
    .name = {"struct base", 11},
    .kind = TYPE_RECORD,
    .size = 24,
    .alignment = 8,
    .as.record = {.field_count = 2, .fields = fields_of_struct_base},
};

Type_Info const *typeinfo_of_struct_base(void) {
    return &info_for_struct_base;
}

// Type info for: 'Named'
static const Type_Record_Field fields_of_Named[3] = {
    {.name = {"base", 4}, .offset = 0, .type = &info_for_struct_base},
    {.name = {"name", 4}, .offset = 24, .type = &info_for_string_view},
    {.name = {"age", 3}, .offset = 40, .type = &info_for_float},
};
static const Type_Info info_for_Named = {
    .name = {"Named", 5},
    .kind = TYPE_RECORD,
    .size = 48,
    .alignment = 8,
    .as.record = {.field_count = 3, .fields = fields_of_Named},
};

Type_Info const *typeinfo_of_Named(void) {
    return &info_for_Named;
}

// Type info for: 'inval'
static const Type_Info info_for_inval = {
    .name = {"inval", 5},
    .kind = TYPE_INVALID,
    .size = 0,
    .alignment = 0,
};

Type_Info const *typeinfo_of_inval(void) {
    return &info_for_inval;
}

// Type info for: '__fsid_t'
static const Type_Record_Field fields_of___fsid_t[1] = {
    {.name = {"__val", 5}, .offset = 0, .type = &info_for_inval},
};
static const Type_Info info_for___fsid_t = {
    .name = {"__fsid_t", 8},
    .kind = TYPE_RECORD,
    .size = 8,
    .alignment = 4,
    .as.record = {.field_count = 1, .fields = fields_of___fsid_t},
};

Type_Info const *typeinfo_of___fsid_t(void) {
    return &info_for___fsid_t;
}

// Type info for: 'char *'
static const Type_Info info_for_char__ = {
    .name = {"char *", 6},
    .kind = TYPE_POINTER,
    .size = 1,
    .alignment = 1,
    .as.pointer = {.inner = &info_for_char},
};

Type_Info const *typeinfo_of_char__(void) {
    return &info_for_char__;
}

// Type info for: 'Type_Integer'
static const Type_Record_Field fields_of_Type_Integer[2] = {
    {.name = {"byte_width", 10}, .offset = 0, .type = &info_for_unsigned_char},
    {.name = {"is_signed", 9}, .offset = 1, .type = &info_for_inval},
};
static const Type_Info info_for_Type_Integer = {
    .name = {"Type_Integer", 12},
    .kind = TYPE_RECORD,
    .size = 2,
    .alignment = 1,
    .as.record = {.field_count = 2, .fields = fields_of_Type_Integer},
};

Type_Info const *typeinfo_of_Type_Integer(void) {
    return &info_for_Type_Integer;
}

// Type info for: 'Type_Real'
static const Type_Record_Field fields_of_Type_Real[1] = {
    {.name = {"byte_width", 10}, .offset = 0, .type = &info_for_unsigned_char},
};
static const Type_Info info_for_Type_Real = {
    .name = {"Type_Real", 9},
    .kind = TYPE_RECORD,
    .size = 1,
    .alignment = 1,
    .as.record = {.field_count = 1, .fields = fields_of_Type_Real},
};

Type_Info const *typeinfo_of_Type_Real(void) {
    return &info_for_Type_Real;
}

// Type info for: 'const Type_Info *'
static const Type_Info info_for_const_Type_Info__ = {
    .name = {"const Type_Info *", 17},
    .kind = TYPE_POINTER,
    .size = 48,
    .alignment = 8,
    .as.pointer = {.inner = &info_for_struct_Type_Info},
};

Type_Info const *typeinfo_of_const_Type_Info__(void) {
    return &info_for_const_Type_Info__;
}

// Type info for: 'Type_Pointer'
static const Type_Record_Field fields_of_Type_Pointer[2] = {
    {.name = {"inner", 5}, .offset = 0, .type = &info_for_const_Type_Info__},
    {.name = {"attrs", 5}, .offset = 8, .type = &info_for_inval},
};
static const Type_Info info_for_Type_Pointer = {
    .name = {"Type_Pointer", 12},
    .kind = TYPE_RECORD,
    .size = 16,
    .alignment = 8,
    .as.record = {.field_count = 2, .fields = fields_of_Type_Pointer},
};

Type_Info const *typeinfo_of_Type_Pointer(void) {
    return &info_for_Type_Pointer;
}

// Type info for: 'const Type_Record_Field *'
static const Type_Info info_for_const_Type_Record_Field__ = {
    .name = {"const Type_Record_Field *", 25},
    .kind = TYPE_POINTER,
    .size = 32,
    .alignment = 8,
    .as.pointer = {.inner = &info_for_Type_Record_Field},
};

Type_Info const *typeinfo_of_const_Type_Record_Field__(void) {
    return &info_for_const_Type_Record_Field__;
}

// Type info for: 'Type_Record'
static const Type_Record_Field fields_of_Type_Record[2] = {
    {.name = {"field_count", 11}, .offset = 0, .type = &info_for_unsigned_long},
    {.name = {"fields", 6}, .offset = 8, .type = &info_for_const_Type_Record_Field__},
};
static const Type_Info info_for_Type_Record = {
    .name = {"Type_Record", 11},
    .kind = TYPE_RECORD,
    .size = 16,
    .alignment = 8,
    .as.record = {.field_count = 2, .fields = fields_of_Type_Record},
};

Type_Info const *typeinfo_of_Type_Record(void) {
    return &info_for_Type_Record;
}

// Type info for: 'const Type_Union_Field *'
static const Type_Info info_for_const_Type_Union_Field__ = {
    .name = {"const Type_Union_Field *", 24},
    .kind = TYPE_POINTER,
    .size = 24,
    .alignment = 8,
    .as.pointer = {.inner = &info_for_Type_Union_Field},
};

Type_Info const *typeinfo_of_const_Type_Union_Field__(void) {
    return &info_for_const_Type_Union_Field__;
}

// Type info for: 'Type_Union'
static const Type_Record_Field fields_of_Type_Union[2] = {
    {.name = {"field_count", 11}, .offset = 0, .type = &info_for_unsigned_long},
    {.name = {"fields", 6}, .offset = 8, .type = &info_for_const_Type_Union_Field__},
};
static const Type_Info info_for_Type_Union = {
    .name = {"Type_Union", 10},
    .kind = TYPE_RECORD,
    .size = 16,
    .alignment = 8,
    .as.record = {.field_count = 2, .fields = fields_of_Type_Union},
};

Type_Info const *typeinfo_of_Type_Union(void) {
    return &info_for_Type_Union;
}

// Type info for: 'Type_Info_As'
static const Type_Union_Field fields_of_Type_Info_As[5] = {
    {.name = {"integer", 7}, .type = &info_for_Type_Integer},
    {.name = {"real", 4}, .type = &info_for_Type_Real},
    {.name = {"pointer", 7}, .type = &info_for_Type_Pointer},
    {.name = {"record", 6}, .type = &info_for_Type_Record},
    {.name = {"union_", 6}, .type = &info_for_Type_Union},
};
static const Type_Info info_for_Type_Info_As = {
    .name = {"Type_Info_As", 12},
    .kind = TYPE_UNION,
    .size = 16,
    .alignment = 8,
    .as.union_ = {.field_count = 5, .fields = fields_of_Type_Info_As},
};

Type_Info const *typeinfo_of_Type_Info_As(void) {
    return &info_for_Type_Info_As;
}

// Type info for: 'struct Type_Info'
static const Type_Record_Field fields_of_struct_Type_Info[5] = {
    {.name = {"name", 4}, .offset = 0, .type = &info_for_string_view},
    {.name = {"kind", 4}, .offset = 16, .type = &info_for_inval},
    {.name = {"size", 4}, .offset = 20, .type = &info_for_unsigned_int},
    {.name = {"alignment", 9}, .offset = 24, .type = &info_for_unsigned_int},
    {.name = {"as", 2}, .offset = 32, .type = &info_for_Type_Info_As},
};
static const Type_Info info_for_struct_Type_Info = {
    .name = {"struct Type_Info", 16},
    .kind = TYPE_RECORD,
    .size = 48,
    .alignment = 8,
    .as.record = {.field_count = 5, .fields = fields_of_struct_Type_Info},
};

Type_Info const *typeinfo_of_struct_Type_Info(void) {
    return &info_for_struct_Type_Info;
}

// Type info for: 'Type_Record_Field'
static const Type_Record_Field fields_of_Type_Record_Field[3] = {
    {.name = {"name", 4}, .offset = 0, .type = &info_for_string_view},
    {.name = {"offset", 6}, .offset = 16, .type = &info_for_unsigned_long},
    {.name = {"type", 4}, .offset = 24, .type = &info_for_const_Type_Info__},
};
static const Type_Info info_for_Type_Record_Field = {
    .name = {"Type_Record_Field", 17},
    .kind = TYPE_RECORD,
    .size = 32,
    .alignment = 8,
    .as.record = {.field_count = 3, .fields = fields_of_Type_Record_Field},
};

Type_Info const *typeinfo_of_Type_Record_Field(void) {
    return &info_for_Type_Record_Field;
}

// Type info for: 'Type_Union_Field'
static const Type_Record_Field fields_of_Type_Union_Field[2] = {
    {.name = {"name", 4}, .offset = 0, .type = &info_for_string_view},
    {.name = {"type", 4}, .offset = 16, .type = &info_for_const_Type_Info__},
};
static const Type_Info info_for_Type_Union_Field = {
    .name = {"Type_Union_Field", 16},
    .kind = TYPE_RECORD,
    .size = 24,
    .alignment = 8,
    .as.record = {.field_count = 2, .fields = fields_of_Type_Union_Field},
};

Type_Info const *typeinfo_of_Type_Union_Field(void) {
    return &info_for_Type_Union_Field;
}

#endif // TYPEINFO_IMPLEMENTATION

